// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsgfttdrhfrzyetjpnmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzZ2Z0dGRyaGZyenlldGpwbm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Mzc4ODUsImV4cCI6MjA2NTExMzg4NX0.QOPQdmNA5KOwveADtNPMeNG_I9KRx2Dw9lH2axEttIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);